### ISSUE TITLE
Getting  http://data.fotorama.io/?version=4.6.0 403 (Forbidden) in console

### ISSUE THREAD

**Issue by naneri** [artpolikarpov/fotorama#382]
GET http://data.fotorama.io/?version=4.6.0 403 (Forbidden) error in console. It seems that Fotorama is sending an ajax call to that URL. And because of error my page keeps on loading. Is there any way to fix this?

**Comment by sapegin** [comment]
Same here.

**Comment by kehezen** [comment]
same for me also..

**Comment by akolpakov** [comment]
+1

**Comment by Dinamiko** [comment]
+1

**Comment by avsolod** [comment]
+1

**Comment by holisticnetworking** [comment]
+1. Can we please fix?

**Comment by FBXWEB** [comment]
Hi There Guys!!.. 

I've know that this issue was posted more than one year, but I had the same problem here with some website's clients, I solved this issue with two steps:

01º - I uploaded to website server a new version of FOTORAMA, I sent the css and jacascript files (fotorama.css and fotorama.js) and put it on same directories for my older files (Please, dont forget, you MUST make a backup of your older versions before change anything)
you can download the fotorama files here: [http://fotorama.io/](http://fotorama.io/)

02º - I've updated my JQUERY.min.. Also I've uploaded a new version of JQUERY.mim.js, at this moment the newest version is JQUERY.MIN-1.12.0.js
You can find this version here: [https://jquery.com/download/](https://jquery.com/download/)

After this steps I solved this problem, in my case I received another kind of error, but was something about my personal script, But just in case you find another error on your browser console, you can fix it easily with some patience and a research about the issue!!..
I hope that this can help!!.. 
SeeYa!
