### ISSUE TITLE
Fotorama’s dimensions of the first image cause bigger image to scale down

### ISSUE THREAD

**Issue by Khrystyna** [artpolikarpov/fotorama#383]
I know from docs that «Fotorama’s dimensions are the dimensions of the first image. Other pictures are scaled proportionally to fit». Is it possible to override this behavior? I have images with different dimensions. I tried to set minheight, height, ratio, but it stills scale to first opened image. If image is small, all other images, even if they are big and can be shown in proper size, are scaled to small size. It's not a problem to scale up smaller image, but it's sad to to lose big image. I should fit into height of container, so setting width, unfortunately, is not good solution for me as portrait photo will not fit then.

**Comment by nicboyde** [comment]
I have the same problem. If the first image loaded is small, all are small, including images intended to be larger - the "display image" in a gallery. I can't see how to force the big image to appear big every time.

Any ideas?

**Comment by nicboyde** [comment]
Problem is intermittent - and something to do with cacheing. No observed occurences until I started serving images marked to be cached (part of a site speed-up exercise). After that, 1:10- 1:20 page loads (and only for new pages, or old pages loaded into a cleared local browser cache) show the key image same size as thumbnails, and only one or two thumbnails show. A simple refresh cures the problem, but it would be much better to show the key image at full size first-off.

I've just installed 4.6.4 to see if problem fixed there. Will report.

**Comment by Khrystyna** [comment]
@nicboyde  Thanks for update. 
Anyway, I am still looking for solution.

**Comment by nicboyde** [comment]
@Khrystyna 

I now use phpthumb to generate the images with the correct sizes, bypassing the fotorama scaling. I don't think that this has cured the problem, but it has certainly made it rarer - so rare that I can't reproduce it myself without disabling the cacheing. The issue is somehow linked to cacheing policy, but I can't work out how. It may be that using phpthumb is slowing down the generation of the smaller images, the thumbnails, thus allowing the larger images, also processed through phpthumb, to arrive first. In most cases.

If it is relevant, I use MODX as the platform CMS and a shared piece of code called phpthumbof. 

Good luck.

**Comment by Khrystyna** [comment]
@nicboyde  Thank you for possible solution :)
