### ISSUE TITLE
Bug with first time loading

### ISSUE THREAD

**Issue by SergeSysoev** [artpolikarpov/fotorama#440]
Hi. There is a bug with first time loading gallery, here screenshot: http://snag.gy/hnMxC.jpg
When I loading secondly and more it isn't. But if I clean cache, it is shows gallery like in screenshot. What I can doing?

**Comment by davidwessman** [comment]
This happens to me as well.
I sets the width of the slider according to the thumbnail size, I feel like it happens when the loading speed is a bit slower.

**Comment by w32blaster** [comment]
Thanks for creating this issue. I also have the same trouble. The problem is that I can't reproduce this bug, because it happens randomly for me. I suspect that this is because Fotorama builds the gallery before images are loaded and their dimensions are not available yet. But I'm not sure, I'll continue trying to debug it.

**Comment by cmb69** [comment]
For what it's worth, I'm experiencing the same issue. By the way, this ticket might be a duplicate of #383.

**Comment by cmb69** [comment]
It appears pull request #445 is supposed to fix this issue.
